services:
  - type: web
    name: vada-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build

  - type: web
    name: vada-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
